### PR TITLE
[Feature] Grant Model popup #3

### LINKED ISSUE #3: Grants Creation Flow
This Modal should pop up for any time that a `Create Grant` button is clicked

funding-create-grant

### PR DESCRIPTION
**Pull request by yashikajotwani12**
Fixes #3

### CODE REVIEW

**Comment by jacobcreech** [comment]
Modal looks good. What are the buttons for placed on the main page?

**Comment by yashikajotwani12** [comment]
> Modal looks good. What are the buttons for placed on the main page?

` Create Grant `  would open to the modal popup
` Connect Wallet ` button would open with a popup,  when the wallet is not connected, [we need to figure that condition].
for now, I have added both of these to the landing page.

**Comment by jacobcreech** [comment]
>Create Grant would open to the modal popup
Connect Wallet button would open with a popup, when the wallet is not connected, [we need to figure that condition].
for now, I have added both of these to the landing page.

Could we remove the buttons until we have the end-to-end flow working? We can stitch it together then

**Comment by yashikajotwani12** [comment]
> > Create Grant would open to the modal popup
> > Connect Wallet button would open with a popup, when the wallet is not connected, [we need to figure that condition].
> > for now, I have added both of these to the landing page.
> 
> Could we remove the buttons until we have the end-to-end flow working? We can stitch it together then

Yeah, sure! I would remove them from the landing page then for now.

**Pull request merged**
