### PR TITLE
Feat: Donations

### PR DESCRIPTION
**Pull request by coszio**
# Context
When donating to a grant (either from a user or from a matcher) we want to deposit the money into the grant account first before releasing it to the grant creator. Once an arbitrary constrain has been cleared (e.g. a deadline has passed), the money will be transferred to the grant creator, else, the grant can be cancelled and the money be refunded to each donor.

## Implementation
A `Donation` will be a PDA derived from a grant and a user, so a user can only have one escrow account per grant to avoid multiple escrow accounts. Users should be able to donate again, which will increase the funds of the `Grant` account.

Another `Link` account will be created along each donation, which will be derived from the grant + donation_count of it to be able 
to track all current donations related to the grant.

To cancel a donation requires that the grant it relates to has already been cancelled.

## Action Items:
- [x] `Donation` struct
- [x] `Donation` creation
- [x] Make sure a user can only have one `Donation` account per grant
- [x] `Grant` release (give the money to the receiver)
- [x] `Donation` cancellation (return the money to the donor)
- [x] Increase the amount donated
- [x] Make sure all `Donation`s related to a grant can be queried without prior knowledge of the users who donated 
- [x] Make sure release and cancel actions can only be made when an admin or DAO authorizes it
- [x] Cancelling a grant enables the cancellation of all donations related to it
- [x] Add helper functions for create/increment a donation, and to cancel grant + refund grant's donations

### CODE REVIEW

**Review by cdhiraj40 — COMMENTED** [review]
Hey @coszio just a small thing, can you add this [error file](https://github.com/solana-developers/solana-grants/pull/21/files#diff-e9851b36c5bfc59a08f175fd226f5e335abd55cb2e131e11854c5e9dbf35591b) in a separate folder named errors? Thats what I did in my PR as there will be different specific error files. Thanks!

**Comment by coszio** [comment]
Great suggestion, I'll make sure to do that when merging with your PR

**Comment by coszio** [comment]
Just merged the changes from #23 which is already on main, which required some refactoring work on the anchor side, and a lot of it on the tests side.

**Review by jpcaulfi — APPROVED** [review]
Program-side looks great!

**Comment by jpcaulfi** [comment]
Did not review app yet btw

**Comment by jacobcreech** [comment]
```
./src/transactions/index.ts:3:31
--
13:33:29.618 | Type error: Cannot find module '../../../target/types/grants_program' or its corresponding type declarations.
13:33:29.618 |  
13:33:29.619 | 1 \| import * as anchor from "@project-serum/anchor";
13:33:29.619 | 2 \| import { Program } from "@project-serum/anchor";
13:33:29.619 | > 3 \| import { GrantsProgram } from "../../../target/types/grants_program";

```

**Comment by jpcaulfi** [comment]
I noticed your test suite doesn't seem to want to run on my local setup:
```shell
ts-mocha -p ./tsconfig.json -t 1000000 tests/suites/donations.test.ts tests/suites/grants.test.ts

  0 passing (0ms)
```

**Comment by jpcaulfi** [comment]
^ nvm got it. Assuming you just run `anchor test` and not `anchor run test` at all

**Review by jpcaulfi — APPROVED** [review]

**Comment by jacobcreech** [comment]
```
Type error: Property 'metadata' does not exist on type '{ version: string; name: string; instructions: { name: string; accounts: { name: string; isMut: boolean; isSigner: boolean; }[]; args: { name: string; type: string; }[]; }[]; accounts: { name: string; type: { kind: string; fields: ({ ...; } | { ...; })[]; }; }[]; types: { ...; }[]; errors: { ...; }[]; }'.
```

**Review by jacobcreech — APPROVED** [review]

**Pull request merged**
