### PR TITLE
feat: add github authentication

### PR DESCRIPTION
**Pull request by Mayank17M**
This PR adds GitHub sign-in and authentication to the website.

image

### CODE REVIEW

**Comment by Mayank17M** [comment]
@jacobcreech can you provide us with the vercel credentials? As you can see with [this commit](https://github.com/solana-developers/solana-grants/pull/28/commits/6fa46ed8b4e461a1a597579eeb5e2035f9d5cd61) some checks and the vercel deployment was failing. I'd like to see the details of the error.

**Comment by jacobcreech** [comment]
That access is a bit too broad. However, here's the error:

```
[4/4] Building fresh packages...
$ husky install
husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Command "yarn install" exited with 1
```

**Comment by Mayank17M** [comment]
Thanks, this should help.

**Comment by Mayank17M** [comment]
Hey @jacobcreech, this PR is ready for review. There are a few things that needs to be done from your side for the GitHub authentication to be running on the Vercel deployment.
- Currently the authentication is running through [this app](https://github.com/apps/solana-grants) on a localhost config.
- Now we can either use this app only while the project is still on Vercel, or you can create another app and use its credentials.
- In any case there needs to be some environment variables set in the project. I've added a [`.env.example`](https://github.com/solana-developers/solana-grants/pull/28/files#diff-f05b4db814aed56db52bbd7a3377a46369e19dd22f7b8dca3330fbac413d51a1), there you can see what all needs to be added.

**Review by jacobcreech — APPROVED** [review]

**Comment by Mayank17M** [comment]
@jacobcreech there seems to be some checks failing, though I didn't make any changes to the code. Can you send the details of the error?

**Pull request merged**
